[tox]
min_version = 4.11

env_list =
    python{310,311,312,313}-django5.2-wagtail{7.0,7.4}
    python{312,313,314}-django6.0-wagtail7.4
    python314-django6.0-wagtailmain

[gh-actions]
python =
    3.10: python310
    3.11: python311
    3.12: python312
    3.13: python313
    3.14: python314

[testenv]
package = wheel
wheel_build_env = .pkg
use_frozen_constraints = true
constrain_package_deps = true

pass_env =
    FORCE_COLOR
    NO_COLOR

setenv =
    PYTHONPATH = {toxinidir}
    DJANGO_SETTINGS_MODULE = tests.settings
    PYTHONDEVMODE = 1
    # use the Python 3.12+ sys.monitoring
    python3.13: COVERAGE_CORE=sysmon
    python3.14: COVERAGE_CORE=sysmon

deps =
    coverage>=7.0,<8.0

    django5.2: Django>=5.2,<5.3
    django6.0: Django>=6.0,<6.1

    wagtail7.0: wagtail>=7.0,<7.1
    wagtail7.4: wagtail>=7.4,<7.5

install_command = python -Im pip install -U {opts} {packages}

commands_pre =
    python {toxinidir}/tests/manage.py migrate

commands =
    python -m coverage run {toxinidir}/tests/manage.py test {posargs: -v 2}

[testenv:coverage-report]
base_python = python3.13
package = skip
deps =
    coverage>=7.0,<8.0
commands =
    python -Im coverage combine
    python -Im coverage report -m

[testenv:interactive]
description = An interactive environment for local testing purposes
base_python = python3.13
package = editable

deps =
    wagtail>=7.0

commands_pre =
    python {toxinidir}/tests/manage.py makemigrations
    python {toxinidir}/tests/manage.py migrate
    python {toxinidir}/tests/manage.py shell -c "from django.contrib.auth import get_user_model;User = get_user_model();(not User.objects.filter(username='admin').exists()) and User.objects.create_superuser('admin', 'super@example.com', 'changeme')"
    python {toxinidir}/tests/manage.py createcachetable

commands =
    {posargs:python {toxinidir}/tests/manage.py runserver 0.0.0.0:8020}

set_env =
    INTERACTIVE = 1

[testenv:wagtailmain]
deps =
    coverage>=7.0,<8.0
    wagtailmain: git+https://github.com/wagtail/wagtail.git@main#egg=Wagtail
